# ç½‘ç«™é…ç½®
Config:
  title: Tabox # ç½‘é¡µæ ‡é¢˜
  logo: favicon.svg # logo å¯ä»¥ä¸º url
  hide: true # éšè—ä¾§æ 
  link: https://tab.fzf404.top # Logo è·³è½¬ç½‘é¡µ

# æœç´¢æ è®¾ç½®
Search:
  ğŸŒŒæ ¡çº§:
    ğŸ«æ ¡å®˜ç½‘: https://www.sylu.edu.cn/
    ğŸ§°æ•™åŠ¡å¤„: https://jwc.sylu.edu.cn/index.htm
    ğŸ“•å›¾ä¹¦é¦†: https://tsg.sylu.edu.cn/
    ğŸ”«å…µå™¨åšç‰©é¦†: https://bqbwg.sylu.edu.cn/
    ğŸ’»ç§‘æŠ€å¤„: https://kjc.sylu.edu.cn/
    â˜æ‹›ç”Ÿå¤„: https://zs.sylu.edu.cn/
    ğŸˆå°±ä¸šå¤„: http://job.sylu.edu.cn/
  ğŸŒé™¢çº§:
    ğŸ“ç ”ç©¶ç”Ÿé™¢: https://yanjiusheng.sylu.edu.cn/
    ğŸ§ªææ–™å­¦ä¸å·¥ç¨‹: https://clygc.sylu.edu.cn/
    ğŸ”©è‡ªåŠ¨åŒ–ä¸ç”µå™¨å·¥ç¨‹: https://zdh.sylu.edu.cn/
    ğŸ’¾ä¿¡æ¯ç§‘å­¦ä¸å·¥ç¨‹: https://sise.sylu.edu.cn/
    ğŸ›¡è£…å¤‡å·¥ç¨‹: https://zbgcxy.sylu.edu.cn/
    ğŸš—æ±½è½¦ä¸äº¤é€š: https://qiche.sylu.edu.cn/index.htm
    ğŸ¨è‰ºæœ¯è®¾è®¡: https://yishu.sylu.edu.cn/
    âš—ç¯åŒ–: https://hhxy.sylu.edu.cn/
    âš™æœºæ¢°: https://jixie.sylu.edu.cn/
    ğŸ“ƒç†å­¦é™¢: https://lxy.sylu.edu.cn/
    ğŸ§”å¤–å›½è¯­: https://waiyu1.sylu.edu.cn/index.htm
    ğŸ¦ç»æµç®¡ç†: https://jjgl.sylu.edu.cn/

# æ ‡ç­¾ç»„
Tabox:
  å­¦æ ¡: # æ ‡ç­¾ç»„ 1
    # æ¨èä½¿ç”¨ https://worldvectorlogo.com/
    logo: logo/xx.svg
    description: å­¦æ ¡å¤§ç½‘ç«™

    å­¦æ ¡å®˜ç½‘:
      - https://www.sylu.edu.cn/
      - æ²ˆé˜³ç†å·¥å¤§å­¦å®˜ç½‘ï¼Œæ¢¦å¼€å§‹çš„åœ°æ–¹
      - https://gimg2.baidu.com/image_search/src=http%3A%2F%2F5b0988e595225.cdn.sohucs.com%2Fimages%2F20180823%2F9fa2ddd80ade45e4919cfa0296815abd.jpeg&refer=http%3A%2F%2F5b0988e595225.cdn.sohucs.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1655282889&t=fa1491f6cdf3751a5883a262982c1f5a
    æ•™åŠ¡å¤„:
      - https://jwc.sylu.edu.cn/index.htm
      - å¤„ç†å­¦ç”Ÿçš„å„ç§é—®é¢˜
      - logo/juc.svg
    ç´ç†å·¥ä½œå®¤:
      - http://ql.sylu.edu.cn/index/#/
      - æ•™åŠ¡å¤„å½’å±ä¸‹çš„ä¸€ä¸ªæŠ€æœ¯å·¥ä½œå®¤
      - logo/ql.png
    å›¢å§”ç®¡ç†ç³»ç»Ÿ:
      - http://xg.sylu.edu.cn/SyluTW/Sys/UserLogin.aspx
      - ç¬¬äºŒè¯¾å ‚æˆç»©æŸ¥è¯¢å¤„
      - logo/tw.svg
    å­¦å·¥ç½‘:
      - http://xg.sylu.edu.cn/SyluXG/Sys/
      - è€ƒè¯•æˆç»©æŸ¥è¯¢å’ŒæŠ¢è¯¾å¤„
      - logo/xgw.svg
    å›¾ä¹¦é¦†:
      - https://tsg.sylu.edu.cn/
      - åœ¨çŸ¥è¯†çš„æµ·æ´‹é¨æ¸¸
      - logo/tsg.svg
    å…µå™¨åšç‰©é¦†:
      - https://bqbwg.sylu.edu.cn/
      - å¸¦ä½ äº†è§£å…µå™¨è¿›åŒ–å²
      - logo/bo.svg
    ç§‘æŠ€å¤„:
      - https://kjc.sylu.edu.cn/
      - æ ¡ç§‘ç ”æˆæœå±•ç¤º
      - logo/kj.svg
    æ‹›ç”Ÿå¤„:
      - https://zs.sylu.edu.cn/
      - äº†è§£å­¦æ ¡çš„æ‹›ç”Ÿæ”¿ç­–
      - logo/zs.svg
    å°±ä¸šå¤„:
      - http://job.sylu.edu.cn/
      - å¸¦ä½ äº†è§£æœ€æ–°å°±ä¸šæ¶ˆæ¯
      - logo/jy.svg
    äººäº‹å¤„:
      - https://rsc.sylu.edu.cn/
      - 
      - logo/rsc.svg
    å›½é™…åˆä½œå¤„:
      - https://gjjlhzc.sylu.edu.cn/
      -
      - logo/gjhz.svg  

  å­¦é™¢: # æ ‡ç­¾ç»„ 2
    logo: logo/xy.svg
    description: å„å­¦é™¢ç½‘ç«™

    ç ”ç©¶ç”Ÿé™¢:
      - https://yanjiusheng.sylu.edu.cn/
      - ç ”ç©¶ç”Ÿçš„ç›¸å…³æ¶ˆæ¯
      - logo/yjs.svg
    ææ–™ä¸å·¥ç¨‹å­¦é™¢:
      - https://clygc.sylu.edu.cn/
      - 
      - logo/cl.svg
    è‡ªåŠ¨åŒ–ä¸ç”µæ°”å·¥ç¨‹å­¦é™¢:
      - https://zdh.sylu.edu.cn/
      - 
      - logo/zdh.svg
    ä¿¡æ¯ç§‘å­¦ä¸å·¥ç¨‹å­¦é™¢:
      - https://sise.sylu.edu.cn/
      - 
      - logo/rj.svg
    è£…å¤‡å·¥ç¨‹å­¦é™¢:
      - https://zbgcxy.sylu.edu.cn/
      - 
      - logo/zb.svg
    æ±½è½¦ä¸äº¤é€šå­¦é™¢:
      - https://qiche.sylu.edu.cn/index.htm
      - 
      - logo/car.svg
    è‰ºæœ¯è®¾è®¡å­¦é™¢:  
      - https://yishu.sylu.edu.cn/
      - 
      - logo/art.svg
    ç¯å¢ƒä¸åŒ–å­¦å·¥ç¨‹å­¦é™¢:
      - https://hhxy.sylu.edu.cn/
      - 
      - logo/hj.svg
    æœºæ¢°å­¦é™¢:
      - https://jixie.sylu.edu.cn/
      -
      - logo/jx.svg
    ç†å­¦é™¢:
      - https://lxy.sylu.edu.cn/
      -
      - logo/lxy.svg
    å¤–å›½è¯­å­¦é™¢:
      - https://waiyu1.sylu.edu.cn/index.htm
      - 
      - logo/wgr.svg
    ç»æµç®¡ç†å­¦é™¢:
      - https://jjgl.sylu.edu.cn/
      - 
      - logo/jjgl.svg
          
  å…¶ä»–:
    logo: logo/qt.svg
    description: æ ¡å›­å…¶ä»–å¹³å°

    åå‹¤å¤„:
      - https://hqjt.sylu.edu.cn/
      - åå‹¤ä¿éšœä¿¡æ¯
      - logo/hq.svg
    åˆ›æ–°åˆ›ä¸šä¸­å¿ƒ:
      - https://cxcyzx.sylu.edu.cn/
      - å¤§å­¦ç”Ÿåˆ›ä¸šå¹³å°
      - logo/cxcy.svg


  Memo: # å¤‡å¿˜å½•
    logo: https://cdn.worldvectorlogo.com/logos/microsoft-teams-1.svg
    description: å¤‡å¿˜å½•

    content: |
      Hello, This is fzf404.
      A full stack developer.
      Here is my website: 
        https://www.fzf404.top
